### ISSUE TITLE
Error when running gProfiler - Failed to profile Java process 

### ISSUE THREAD

**Issue by rdar-lab** [Granulate/gprofiler#136]
```
[18:02:35] Failed to profile Java process 2640526
Traceback (most recent call last):
  File "/app/gprofiler/java.py", line 356, in snapshot
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/gprofiler/java.py", line 300, in _profile_process
    return self._profile_ap_process(ap_proc)
  File "/app/gprofiler/java.py", line 303, in _profile_ap_process
    started = ap_proc.start_async_profiler(self._interval)
  File "/app/gprofiler/java.py", line 206, in start_async_profiler
    self._run_async_profiler(start_cmd)
  File "/app/gprofiler/java.py", line 198, in _run_async_profiler
    raise JattachException(e.returncode, e.cmd, e.stdout, e.stderr, self.process.pid, ap_log) from None
gprofiler.java.JattachException: Command '['/app/gprofiler/resources/java/jattach', '2640526', 'load', '/tmp/gprofiler_tmp/async-profiler/libasyncProfiler.so', 'true', 'start,event=itimer,file=/tmp/gprofiler_tmp/tmpb5lwtt4g/async-profiler-2640526.output,collapsed,ann,sig,interval=90909090,framebuf=2000000,log=/tmp/gprofiler_tmp/tmpb5lwtt4g/async-profiler-2640526.log']' returned non-zero exit status 255. 
stdout: b'Connected to remote JVM\nJVM response code = -1\n/tmp/gprofiler_tmp/async-profiler/libasyncProfiler.so was not loaded.\nError loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/gprofiler_tmp/async-profiler/libasyncProfiler.so)\n\n'
stderr: b''
Java PID: 2640526
async-profiler log:
```

**Comment by Jongy** [comment]
`libasyncProfiler.so` indeed depends on stdc++:
```
root@jong-XPS-15-7590:/app# ldd /app/gprofiler/resources/java/libasyncProfiler.so 
	linux-vdso.so.1 (0x00007ffe779ee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7e8fcff000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7e8fcdc000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7e8fcd1000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7e8faf0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7e8f9a1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7e8f986000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e8f792000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7e8ff58000)
```

It can be solved by building AP with `-static-libstdc++` or by bundling it with the DSO (and making sure it's in the `LD_LIBRARY_PATH` / using `RPATH`). If that's the issue, it's something we can take care of for the next release :)

Can you please share some more details about the environment? If you could share `/proc/pid/maps` of the Java process (at least of all the loaded DSOs) it can be helpful to understand.

**Comment by Jongy** [comment]
@rdar-lab we have released https://github.com/Granulate/gprofiler/releases/tag/1.1.6 which should solve the problem - can you please try running gProfiler again?

**Comment by rdar-lab** [comment]
Just pulled the latest tag of the docker image and the issue is still happening.
But I think it may be happening because I have pycharm running on the same machine  (according to the PID on the error)

**Comment by Jongy** [comment]
> But I think it may be happening because I have pycharm running on the same machine (according to the PID on the error)

Yes, pycharm is Java-based and gProfiler will try to profile it after detecting that :sweat_smile: 

It is weird that the error persists, though. I will investigate it.

**Comment by Jongy** [comment]
Managed to run gProfiler on IntelliJ
